### ISSUE TITLE
Native bignum support, math-fixnum was removed from Emacs 27

### ISSUE THREAD

**Issue by nigredo-tori** [kanru/uuidgen-el#2]
Calling `uuidgen` with the current Emacs snapshot produces:
```
condition-case: Symbol’s function definition is void: math-fixnum
```
GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8) of 2019-12-23

See https://github.com/emacs-mirror/emacs/commit/1bc1672f77d15f5f2cda29ce8ce4806bbb6ff71a#diff-81e14a18908dd0a9d22d43ed8109ee8e . I'm not really familiar with Elisp, so I can't say whether any other changes could have impacted this package.

**Comment by kanru** [comment]
Thanks for the report!

**Comment by kanru** [comment]
Emacs 27 has native bignum support.

https://github.com/emacs-mirror/emacs/blob/41450a8ea5a156a34f6641a0768cadb174fa261c/etc/NEWS.27#L2975-L3001
